//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allocat.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int ErrorId { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorBody { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
        public string StackTrace { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Transaction Transaction { get; set; }
        public virtual User User { get; set; }
    }
}
