//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allocat.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TissueBankCreditCard
    {
        public int TissueBankCreditCardId { get; set; }
        public Nullable<int> TissueBankId { get; set; }
        public string CreditCardNumber { get; set; }
    
        public virtual TissueBank TissueBank { get; set; }
    }
}
