//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allocat.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Error = new HashSet<Error>();
        }
    
        public int TransactionId { get; set; }
        public string AuthTransactionId { get; set; }
        public string AuthCode { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> TransactionInitiateDate { get; set; }
        public Nullable<System.DateTime> TransactionCompleteDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TissueBankId { get; set; }
        public string RequestBody { get; set; }
        public string ResponseBody { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Error> Error { get; set; }
        public virtual Status Status { get; set; }
        public virtual TissueBank TissueBank { get; set; }
        public virtual User User { get; set; }
    }
}
