//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allocat.WebApi.CustomService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.BankAccount BankAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.CreditCard CardInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPaymentProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.CustomerType CustomerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.AddressInfo HomeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantCustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.AddressInfo OfficeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.PaymentType PaymentTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.BankAccount BankAccount {
            get {
                return this.BankAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountField, value) != true)) {
                    this.BankAccountField = value;
                    this.RaisePropertyChanged("BankAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.CreditCard CardInfo {
            get {
                return this.CardInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardInfoField, value) != true)) {
                    this.CardInfoField = value;
                    this.RaisePropertyChanged("CardInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerPaymentProfileId {
            get {
                return this.CustomerPaymentProfileIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPaymentProfileIdField, value) != true)) {
                    this.CustomerPaymentProfileIdField = value;
                    this.RaisePropertyChanged("CustomerPaymentProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.CustomerType CustomerType {
            get {
                return this.CustomerTypeField;
            }
            set {
                if ((this.CustomerTypeField.Equals(value) != true)) {
                    this.CustomerTypeField = value;
                    this.RaisePropertyChanged("CustomerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.AddressInfo HomeAddress {
            get {
                return this.HomeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeAddressField, value) != true)) {
                    this.HomeAddressField = value;
                    this.RaisePropertyChanged("HomeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantCustomerId {
            get {
                return this.MerchantCustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantCustomerIdField, value) != true)) {
                    this.MerchantCustomerIdField = value;
                    this.RaisePropertyChanged("MerchantCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.AddressInfo OfficeAddress {
            get {
                return this.OfficeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeAddressField, value) != true)) {
                    this.OfficeAddressField = value;
                    this.RaisePropertyChanged("OfficeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.PaymentType PaymentType {
            get {
                return this.PaymentTypeField;
            }
            set {
                if ((this.PaymentTypeField.Equals(value) != true)) {
                    this.PaymentTypeField = value;
                    this.RaisePropertyChanged("PaymentType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net")]
    [System.SerializableAttribute()]
    public partial class BankAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ECheckTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameOnAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoutingNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountTypeField, value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccountNumber {
            get {
                return this.BankAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountNumberField, value) != true)) {
                    this.BankAccountNumberField = value;
                    this.RaisePropertyChanged("BankAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ECheckType {
            get {
                return this.ECheckTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ECheckTypeField, value) != true)) {
                    this.ECheckTypeField = value;
                    this.RaisePropertyChanged("ECheckType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameOnAccount {
            get {
                return this.NameOnAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.NameOnAccountField, value) != true)) {
                    this.NameOnAccountField = value;
                    this.RaisePropertyChanged("NameOnAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoutingNumber {
            get {
                return this.RoutingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoutingNumberField, value) != true)) {
                    this.RoutingNumberField = value;
                    this.RaisePropertyChanged("RoutingNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCard", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net")]
    [System.SerializableAttribute()]
    public partial class CreditCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditCardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpiryDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardCode {
            get {
                return this.CardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardCodeField, value) != true)) {
                    this.CardCodeField = value;
                    this.RaisePropertyChanged("CardCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditCardNumber {
            get {
                return this.CreditCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardNumberField, value) != true)) {
                    this.CreditCardNumberField = value;
                    this.RaisePropertyChanged("CreditCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreditCardType {
            get {
                return this.CreditCardTypeField;
            }
            set {
                if ((this.CreditCardTypeField.Equals(value) != true)) {
                    this.CreditCardTypeField = value;
                    this.RaisePropertyChanged("CreditCardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateField, value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressInfo", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net")]
    [System.SerializableAttribute()]
    public partial class AddressInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaxNumber {
            get {
                return this.FaxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNumberField, value) != true)) {
                    this.FaxNumberField = value;
                    this.RaisePropertyChanged("FaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerType", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net")]
    public enum CustomerType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Individual = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Business = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentType", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net")]
    public enum PaymentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreditCard = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ECheck = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResCustomerProfile", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities.ResponseEntities")]
    [System.SerializableAttribute()]
    public partial class ResCustomerProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CustomerPaymentProfileIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CustomerShippingProfileIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.ResTransaction TransactionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CustomerPaymentProfileIds {
            get {
                return this.CustomerPaymentProfileIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPaymentProfileIdsField, value) != true)) {
                    this.CustomerPaymentProfileIdsField = value;
                    this.RaisePropertyChanged("CustomerPaymentProfileIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerProfileId {
            get {
                return this.CustomerProfileIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerProfileIdField, value) != true)) {
                    this.CustomerProfileIdField = value;
                    this.RaisePropertyChanged("CustomerProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CustomerShippingProfileIds {
            get {
                return this.CustomerShippingProfileIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerShippingProfileIdsField, value) != true)) {
                    this.CustomerShippingProfileIdsField = value;
                    this.RaisePropertyChanged("CustomerShippingProfileIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId {
            get {
                return this.RefIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RefIdField, value) != true)) {
                    this.RefIdField = value;
                    this.RaisePropertyChanged("RefId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionToken {
            get {
                return this.SessionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTokenField, value) != true)) {
                    this.SessionTokenField = value;
                    this.RaisePropertyChanged("SessionToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.ResTransaction Transaction {
            get {
                return this.TransactionField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionField, value) != true)) {
                    this.TransactionField = value;
                    this.RaisePropertyChanged("Transaction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResTransaction", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities.ResponseEntities")]
    [System.SerializableAttribute()]
    public partial class ResTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode {
            get {
                return this.AuthCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthCodeField, value) != true)) {
                    this.AuthCodeField = value;
                    this.RaisePropertyChanged("AuthCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorText {
            get {
                return this.ErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTextField, value) != true)) {
                    this.ErrorTextField = value;
                    this.RaisePropertyChanged("ErrorText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDescription {
            get {
                return this.MessageDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDescriptionField, value) != true)) {
                    this.MessageDescriptionField = value;
                    this.RaisePropertyChanged("MessageDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities.Exceptions")]
    [System.SerializableAttribute()]
    public partial class CustomException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InnerExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InnerException {
            get {
                return this.InnerExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionField, value) != true)) {
                    this.InnerExceptionField = value;
                    this.RaisePropertyChanged("InnerException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerPaymentProfile", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net")]
    [System.SerializableAttribute()]
    public partial class CustomerPaymentProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.AddressInfo BillToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.CreditCard CardInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPaymentProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isUpdateCreditCardInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.AddressInfo BillTo {
            get {
                return this.BillToField;
            }
            set {
                if ((object.ReferenceEquals(this.BillToField, value) != true)) {
                    this.BillToField = value;
                    this.RaisePropertyChanged("BillTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.CreditCard CardInfo {
            get {
                return this.CardInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardInfoField, value) != true)) {
                    this.CardInfoField = value;
                    this.RaisePropertyChanged("CardInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerPaymentProfileId {
            get {
                return this.CustomerPaymentProfileIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPaymentProfileIdField, value) != true)) {
                    this.CustomerPaymentProfileIdField = value;
                    this.RaisePropertyChanged("CustomerPaymentProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerProfileId {
            get {
                return this.CustomerProfileIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerProfileIdField, value) != true)) {
                    this.CustomerProfileIdField = value;
                    this.RaisePropertyChanged("CustomerProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isUpdateCreditCardInfo {
            get {
                return this.isUpdateCreditCardInfoField;
            }
            set {
                if ((this.isUpdateCreditCardInfoField.Equals(value) != true)) {
                    this.isUpdateCreditCardInfoField = value;
                    this.RaisePropertyChanged("isUpdateCreditCardInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShippingAddress", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities.ResponseEntities")]
    [System.SerializableAttribute()]
    public partial class ShippingAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAddressId {
            get {
                return this.CustomerAddressIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressIdField, value) != true)) {
                    this.CustomerAddressIdField = value;
                    this.RaisePropertyChanged("CustomerAddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaxNumber {
            get {
                return this.FaxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNumberField, value) != true)) {
                    this.FaxNumberField = value;
                    this.RaisePropertyChanged("FaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResCustomerProfileDetails", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities.ResponseEntities")]
    [System.SerializableAttribute()]
    public partial class ResCustomerProfileDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantCustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.PaymentProfile[] PaymentPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.ShippingAddress[] ShippingProfilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SubscriptionIdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerProfileId {
            get {
                return this.CustomerProfileIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerProfileIdField, value) != true)) {
                    this.CustomerProfileIdField = value;
                    this.RaisePropertyChanged("CustomerProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantCustomerId {
            get {
                return this.MerchantCustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantCustomerIdField, value) != true)) {
                    this.MerchantCustomerIdField = value;
                    this.RaisePropertyChanged("MerchantCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.PaymentProfile[] PaymentP {
            get {
                return this.PaymentPField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentPField, value) != true)) {
                    this.PaymentPField = value;
                    this.RaisePropertyChanged("PaymentP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefId {
            get {
                return this.RefIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RefIdField, value) != true)) {
                    this.RefIdField = value;
                    this.RaisePropertyChanged("RefId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionToken {
            get {
                return this.SessionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTokenField, value) != true)) {
                    this.SessionTokenField = value;
                    this.RaisePropertyChanged("SessionToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.ShippingAddress[] ShippingProfiles {
            get {
                return this.ShippingProfilesField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingProfilesField, value) != true)) {
                    this.ShippingProfilesField = value;
                    this.RaisePropertyChanged("ShippingProfiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SubscriptionIds {
            get {
                return this.SubscriptionIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriptionIdsField, value) != true)) {
                    this.SubscriptionIdsField = value;
                    this.RaisePropertyChanged("SubscriptionIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentProfile", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities.ResponseEntities")]
    [System.SerializableAttribute()]
    public partial class PaymentProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Allocat.WebApi.CustomService.ShippingAddress BillToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DefaultPaymentProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentProfileIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Allocat.WebApi.CustomService.ShippingAddress BillTo {
            get {
                return this.BillToField;
            }
            set {
                if ((object.ReferenceEquals(this.BillToField, value) != true)) {
                    this.BillToField = value;
                    this.RaisePropertyChanged("BillTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerType {
            get {
                return this.CustomerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTypeField, value) != true)) {
                    this.CustomerTypeField = value;
                    this.RaisePropertyChanged("CustomerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DefaultPaymentProfile {
            get {
                return this.DefaultPaymentProfileField;
            }
            set {
                if ((this.DefaultPaymentProfileField.Equals(value) != true)) {
                    this.DefaultPaymentProfileField = value;
                    this.RaisePropertyChanged("DefaultPaymentProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentItem {
            get {
                return this.PaymentItemField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentItemField, value) != true)) {
                    this.PaymentItemField = value;
                    this.RaisePropertyChanged("PaymentItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentProfileId {
            get {
                return this.PaymentProfileIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentProfileIdField, value) != true)) {
                    this.PaymentProfileIdField = value;
                    this.RaisePropertyChanged("PaymentProfileId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResTransactionDetails", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
        "essEntities.ResponseEntities")]
    [System.SerializableAttribute()]
    public partial class ResTransactionDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AuthAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SettleAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SubmitTimeLocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AuthAmount {
            get {
                return this.AuthAmountField;
            }
            set {
                if ((this.AuthAmountField.Equals(value) != true)) {
                    this.AuthAmountField = value;
                    this.RaisePropertyChanged("AuthAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorText {
            get {
                return this.ErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTextField, value) != true)) {
                    this.ErrorTextField = value;
                    this.RaisePropertyChanged("ErrorText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDescription {
            get {
                return this.MessageDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDescriptionField, value) != true)) {
                    this.MessageDescriptionField = value;
                    this.RaisePropertyChanged("MessageDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SettleAmount {
            get {
                return this.SettleAmountField;
            }
            set {
                if ((this.SettleAmountField.Equals(value) != true)) {
                    this.SettleAmountField = value;
                    this.RaisePropertyChanged("SettleAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SubmitTimeLocal {
            get {
                return this.SubmitTimeLocalField;
            }
            set {
                if ((this.SubmitTimeLocalField.Equals(value) != true)) {
                    this.SubmitTimeLocalField = value;
                    this.RaisePropertyChanged("SubmitTimeLocal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionStatus {
            get {
                return this.TransactionStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionStatusField, value) != true)) {
                    this.TransactionStatusField = value;
                    this.RaisePropertyChanged("TransactionStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTypeField, value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomService.IAllocatCustomService")]
    public interface IAllocatCustomService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/RegisterCustomerAndChargeProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/RegisterCustomerAndChargeProfileResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(Allocat.WebApi.CustomService.CustomException), Action="http://tempuri.org/IAllocatCustomService/RegisterCustomerAndChargeProfileCustomEx" +
            "ceptionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
            "essEntities.Exceptions")]
        Allocat.WebApi.CustomService.ResCustomerProfile RegisterCustomerAndChargeProfile(Allocat.WebApi.CustomService.Customer objCustomer, decimal AmountToBeCharged);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/RegisterCustomerAndChargeProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/RegisterCustomerAndChargeProfileResponse" +
            "")]
        System.Threading.Tasks.Task<Allocat.WebApi.CustomService.ResCustomerProfile> RegisterCustomerAndChargeProfileAsync(Allocat.WebApi.CustomService.Customer objCustomer, decimal AmountToBeCharged);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/ChargeCustomerProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/ChargeCustomerProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Allocat.WebApi.CustomService.CustomException), Action="http://tempuri.org/IAllocatCustomService/ChargeCustomerProfileCustomExceptionFaul" +
            "t", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
            "essEntities.Exceptions")]
        Allocat.WebApi.CustomService.ResTransaction ChargeCustomerProfile(string CustomerProfileId, string CustomerPaymentProfileId, decimal AmountToBeCharged);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/ChargeCustomerProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/ChargeCustomerProfileResponse")]
        System.Threading.Tasks.Task<Allocat.WebApi.CustomService.ResTransaction> ChargeCustomerProfileAsync(string CustomerProfileId, string CustomerPaymentProfileId, decimal AmountToBeCharged);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/UpdateCustomerProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/UpdateCustomerProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Allocat.WebApi.CustomService.CustomException), Action="http://tempuri.org/IAllocatCustomService/UpdateCustomerProfileCustomExceptionFaul" +
            "t", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
            "essEntities.Exceptions")]
        bool UpdateCustomerProfile(string customerProfileId, string merchantCustomerId, string description, string newEmailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/UpdateCustomerProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/UpdateCustomerProfileResponse")]
        System.Threading.Tasks.Task<bool> UpdateCustomerProfileAsync(string customerProfileId, string merchantCustomerId, string description, string newEmailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/UpdateCustomerPaymentProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/UpdateCustomerPaymentProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Allocat.WebApi.CustomService.CustomException), Action="http://tempuri.org/IAllocatCustomService/UpdateCustomerPaymentProfileCustomExcept" +
            "ionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
            "essEntities.Exceptions")]
        bool UpdateCustomerPaymentProfile(Allocat.WebApi.CustomService.CustomerPaymentProfile objCustomerPaymentProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/UpdateCustomerPaymentProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/UpdateCustomerPaymentProfileResponse")]
        System.Threading.Tasks.Task<bool> UpdateCustomerPaymentProfileAsync(Allocat.WebApi.CustomService.CustomerPaymentProfile objCustomerPaymentProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/UpdateCustomerShipingAddress", ReplyAction="http://tempuri.org/IAllocatCustomService/UpdateCustomerShipingAddressResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Allocat.WebApi.CustomService.CustomException), Action="http://tempuri.org/IAllocatCustomService/UpdateCustomerShipingAddressCustomExcept" +
            "ionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
            "essEntities.Exceptions")]
        bool UpdateCustomerShipingAddress(string customerProfileID, string customerAddressId, Allocat.WebApi.CustomService.ShippingAddress objShippingAddress, Allocat.WebApi.CustomService.CreditCard objCardInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/UpdateCustomerShipingAddress", ReplyAction="http://tempuri.org/IAllocatCustomService/UpdateCustomerShipingAddressResponse")]
        System.Threading.Tasks.Task<bool> UpdateCustomerShipingAddressAsync(string customerProfileID, string customerAddressId, Allocat.WebApi.CustomService.ShippingAddress objShippingAddress, Allocat.WebApi.CustomService.CreditCard objCardInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/RetrieveCustomerProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/RetrieveCustomerProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Allocat.WebApi.CustomService.CustomException), Action="http://tempuri.org/IAllocatCustomService/RetrieveCustomerProfileCustomExceptionFa" +
            "ult", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
            "essEntities.Exceptions")]
        Allocat.WebApi.CustomService.ResCustomerProfileDetails RetrieveCustomerProfile(string customerProfileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/RetrieveCustomerProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/RetrieveCustomerProfileResponse")]
        System.Threading.Tasks.Task<Allocat.WebApi.CustomService.ResCustomerProfileDetails> RetrieveCustomerProfileAsync(string customerProfileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/RetrieveTransactionDetails", ReplyAction="http://tempuri.org/IAllocatCustomService/RetrieveTransactionDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Allocat.WebApi.CustomService.CustomException), Action="http://tempuri.org/IAllocatCustomService/RetrieveTransactionDetailsCustomExceptio" +
            "nFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
            "essEntities.Exceptions")]
        Allocat.WebApi.CustomService.ResTransactionDetails RetrieveTransactionDetails(string transactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/RetrieveTransactionDetails", ReplyAction="http://tempuri.org/IAllocatCustomService/RetrieveTransactionDetailsResponse")]
        System.Threading.Tasks.Task<Allocat.WebApi.CustomService.ResTransactionDetails> RetrieveTransactionDetailsAsync(string transactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/DeleteCustomerProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/DeleteCustomerProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Allocat.WebApi.CustomService.CustomException), Action="http://tempuri.org/IAllocatCustomService/DeleteCustomerProfileCustomExceptionFaul" +
            "t", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
            "essEntities.Exceptions")]
        bool DeleteCustomerProfile(string customerProfileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/DeleteCustomerProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/DeleteCustomerProfileResponse")]
        System.Threading.Tasks.Task<bool> DeleteCustomerProfileAsync(string customerProfileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/DeleteCustomerPaymentProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/DeleteCustomerPaymentProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Allocat.WebApi.CustomService.CustomException), Action="http://tempuri.org/IAllocatCustomService/DeleteCustomerPaymentProfileCustomExcept" +
            "ionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
            "essEntities.Exceptions")]
        bool DeleteCustomerPaymentProfile(string customerProfileId, string customerPaymentProfileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/DeleteCustomerPaymentProfile", ReplyAction="http://tempuri.org/IAllocatCustomService/DeleteCustomerPaymentProfileResponse")]
        System.Threading.Tasks.Task<bool> DeleteCustomerPaymentProfileAsync(string customerProfileId, string customerPaymentProfileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/DeleteCustomerShippingAddress", ReplyAction="http://tempuri.org/IAllocatCustomService/DeleteCustomerShippingAddressResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Allocat.WebApi.CustomService.CustomException), Action="http://tempuri.org/IAllocatCustomService/DeleteCustomerShippingAddressCustomExcep" +
            "tionFault", Name="CustomException", Namespace="http://schemas.datacontract.org/2004/07/Allocat.CustomService.Authorize.Net.Busin" +
            "essEntities.Exceptions")]
        bool DeleteCustomerShippingAddress(string customerProfileId, string customerAddressId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllocatCustomService/DeleteCustomerShippingAddress", ReplyAction="http://tempuri.org/IAllocatCustomService/DeleteCustomerShippingAddressResponse")]
        System.Threading.Tasks.Task<bool> DeleteCustomerShippingAddressAsync(string customerProfileId, string customerAddressId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAllocatCustomServiceChannel : Allocat.WebApi.CustomService.IAllocatCustomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllocatCustomServiceClient : System.ServiceModel.ClientBase<Allocat.WebApi.CustomService.IAllocatCustomService>, Allocat.WebApi.CustomService.IAllocatCustomService {
        
        public AllocatCustomServiceClient() {
        }
        
        public AllocatCustomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllocatCustomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllocatCustomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllocatCustomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Allocat.WebApi.CustomService.ResCustomerProfile RegisterCustomerAndChargeProfile(Allocat.WebApi.CustomService.Customer objCustomer, decimal AmountToBeCharged) {
            return base.Channel.RegisterCustomerAndChargeProfile(objCustomer, AmountToBeCharged);
        }
        
        public System.Threading.Tasks.Task<Allocat.WebApi.CustomService.ResCustomerProfile> RegisterCustomerAndChargeProfileAsync(Allocat.WebApi.CustomService.Customer objCustomer, decimal AmountToBeCharged) {
            return base.Channel.RegisterCustomerAndChargeProfileAsync(objCustomer, AmountToBeCharged);
        }
        
        public Allocat.WebApi.CustomService.ResTransaction ChargeCustomerProfile(string CustomerProfileId, string CustomerPaymentProfileId, decimal AmountToBeCharged) {
            return base.Channel.ChargeCustomerProfile(CustomerProfileId, CustomerPaymentProfileId, AmountToBeCharged);
        }
        
        public System.Threading.Tasks.Task<Allocat.WebApi.CustomService.ResTransaction> ChargeCustomerProfileAsync(string CustomerProfileId, string CustomerPaymentProfileId, decimal AmountToBeCharged) {
            return base.Channel.ChargeCustomerProfileAsync(CustomerProfileId, CustomerPaymentProfileId, AmountToBeCharged);
        }
        
        public bool UpdateCustomerProfile(string customerProfileId, string merchantCustomerId, string description, string newEmailId) {
            return base.Channel.UpdateCustomerProfile(customerProfileId, merchantCustomerId, description, newEmailId);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCustomerProfileAsync(string customerProfileId, string merchantCustomerId, string description, string newEmailId) {
            return base.Channel.UpdateCustomerProfileAsync(customerProfileId, merchantCustomerId, description, newEmailId);
        }
        
        public bool UpdateCustomerPaymentProfile(Allocat.WebApi.CustomService.CustomerPaymentProfile objCustomerPaymentProfile) {
            return base.Channel.UpdateCustomerPaymentProfile(objCustomerPaymentProfile);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCustomerPaymentProfileAsync(Allocat.WebApi.CustomService.CustomerPaymentProfile objCustomerPaymentProfile) {
            return base.Channel.UpdateCustomerPaymentProfileAsync(objCustomerPaymentProfile);
        }
        
        public bool UpdateCustomerShipingAddress(string customerProfileID, string customerAddressId, Allocat.WebApi.CustomService.ShippingAddress objShippingAddress, Allocat.WebApi.CustomService.CreditCard objCardInfo) {
            return base.Channel.UpdateCustomerShipingAddress(customerProfileID, customerAddressId, objShippingAddress, objCardInfo);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCustomerShipingAddressAsync(string customerProfileID, string customerAddressId, Allocat.WebApi.CustomService.ShippingAddress objShippingAddress, Allocat.WebApi.CustomService.CreditCard objCardInfo) {
            return base.Channel.UpdateCustomerShipingAddressAsync(customerProfileID, customerAddressId, objShippingAddress, objCardInfo);
        }
        
        public Allocat.WebApi.CustomService.ResCustomerProfileDetails RetrieveCustomerProfile(string customerProfileId) {
            return base.Channel.RetrieveCustomerProfile(customerProfileId);
        }
        
        public System.Threading.Tasks.Task<Allocat.WebApi.CustomService.ResCustomerProfileDetails> RetrieveCustomerProfileAsync(string customerProfileId) {
            return base.Channel.RetrieveCustomerProfileAsync(customerProfileId);
        }
        
        public Allocat.WebApi.CustomService.ResTransactionDetails RetrieveTransactionDetails(string transactionId) {
            return base.Channel.RetrieveTransactionDetails(transactionId);
        }
        
        public System.Threading.Tasks.Task<Allocat.WebApi.CustomService.ResTransactionDetails> RetrieveTransactionDetailsAsync(string transactionId) {
            return base.Channel.RetrieveTransactionDetailsAsync(transactionId);
        }
        
        public bool DeleteCustomerProfile(string customerProfileId) {
            return base.Channel.DeleteCustomerProfile(customerProfileId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCustomerProfileAsync(string customerProfileId) {
            return base.Channel.DeleteCustomerProfileAsync(customerProfileId);
        }
        
        public bool DeleteCustomerPaymentProfile(string customerProfileId, string customerPaymentProfileId) {
            return base.Channel.DeleteCustomerPaymentProfile(customerProfileId, customerPaymentProfileId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCustomerPaymentProfileAsync(string customerProfileId, string customerPaymentProfileId) {
            return base.Channel.DeleteCustomerPaymentProfileAsync(customerProfileId, customerPaymentProfileId);
        }
        
        public bool DeleteCustomerShippingAddress(string customerProfileId, string customerAddressId) {
            return base.Channel.DeleteCustomerShippingAddress(customerProfileId, customerAddressId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCustomerShippingAddressAsync(string customerProfileId, string customerAddressId) {
            return base.Channel.DeleteCustomerShippingAddressAsync(customerProfileId, customerAddressId);
        }
    }
}
